apiVersion: v1
kind: Secret
metadata:
  name: azure-config-file
  namespace: external-dns
stringData:
  azure.json: |
    {
      "tenantId": "56122972-ef61-4781-bbdb-9e9c2c9ec7a5",
      "subscriptionId": "09fb16e3-874d-4121-b09f-9fc3e61ed5e0",
      "resourceGroup": "rg-aks-dev",
      "useManagedIdentityExtension": true
    }
