# Default values for External Secrets wrapper chart.
# All values for the upstream external-secrets chart must be nested under the 'external-secrets' key.
external-secrets:
  # Install CRDs automatically as part of the chart release
  installCRDs: true
  
  replicaCount: 1
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
