ingress-nginx:
  controller:
    replicaCount: 2
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    ingressClassResource:
      default: true
      name: nginx
    config:
      use-forwarded-headers: "true"
