apiVersion: v2
name: cert-manager-addon
description: A Helm chart wrapper for the cert-manager operator.
type: application
version: 1.0.0
appVersion: "1.14.4"
dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
