apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addons
  source:
    # IMPORTANT: Replace this repoURL with your actual Git repository URL
    repoURL: 'https://github.com/whoemai/git_addons.git'
    targetRevision: HEAD
    path: addons/external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    # Deploy to the 'external-secrets' namespace
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
