apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for cluster-wide infrastructure addons (KEDA, External Secrets, External DNS, etc.)
  sourceRepos:
    - 'https://github.com/whoemai/git_addons.git'
    - 'https://kedacore.github.io/charts'
    - 'https://charts.external-secrets.io'
    - 'https://kubernetes-sigs.github.io/external-dns/'
    - 'https://charts.jetstack.io'
    - 'https://kubernetes.github.io/ingress-nginx'
  
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
