apiVersion: v2
name: keda-addon
description: A Helm chart wrapper for the KEDA operator and associated resources.
type: application
version: 1.0.0
appVersion: "2.14.0"
dependencies:
  - name: keda
    version: 2.14.0
    repository: https://kedacore.github.io/charts
